name: install nodejs
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install nodejs
        uses: actions/setup-node@v4
      - name: fetch repository
        uses: actions/checkout@v4
      # met des elements en cache, le cache permet de gagner du temps lors des prochaines utilisations du workflow
      # on place configure cache avant  install dependancies cafin que le cache prenne en compte les dépendance
      - name: configure cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ hashFiles('./vite-project/package-lock.json') }}
          path: ./vite-project/.npm
        # on installe les dépendances qui seront mis en cache
      - name: install dependancies
        run: npm ci --cache .npm --prefer-offline
        working-directory: ./vite-project
